# Generated by Django 5.0.1 on 2024-01-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_tareas_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
