# Generated by Django 5.0.1 on 2024-01-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_tarea_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
